### ISSUE TITLE
Need ability to make LO/HI-HI/LO Data statements

### ISSUE THREAD

**Issue by oziphantom** [fadden/6502bench#10]
There are 3 cases
LabelA .byte LO
LabelB .byte HI,LO,HI,LO,HI,LO
to which you want to be able to get
LabelB = * +1
LabelA .word HILO,HILO,HILO

LabelA .byte lo,lo,lo,lo,lo,lo,lo,lo
LabelB .byte hi,hi,hi,hi,hi,hi,hi,hi
Which then becomes 
LabelA .byte <lohi,<lohi,<lohi,<lohi,<lohi,<lohi,<lohi,<lohi
LabelB .byte >lohi,>lohi,>lohi,>lohi,>lohi,>lohi,>lohi,>lohi
And also the other case
LabelA .byte hi,hi,hi,hi,hi,hi,hi,hi
LabelB .byte lo,lo,lo,lo,lo,lo,lo,lo
Which then becomes
LabelA .byte >lohi,>lohi,>lohi,>lohi,>lohi,>lohi,>lohi,>lohi
LabelB .byte <lohi,<lohi,<lohi,<lohi,<lohi,<lohi,<lohi,<lohi

Where the hilo are labels

these also need a STACK modifier so the label becomes the WORD address +1 and then the bytes are -1 of the address, ready for a RTS hack

**Comment by fadden** [comment]
For 16-bit addresses where the bytes are adjacent, this is easy: as in the tutorial and demo video, format the data as 16-bit little-endian addresses, and it'll pick up labels automatically.  If the bytes are in big-endian order, use the 16-bit big-endian format instead.

For 16-bit addresses that are split into two tables of equal length, you have to specify the symbol for each item.  You can see an example of this in the A2-Amper-fdraw example, which uses a split jump table.  These are RTS addresses, so they're offset by -1 (which is applied automatically):

    jmptabl  .dd1    <h_new-1
             .dd1    <h_hgr-1
             .dd1    <h_hgr2-1
             .dd1    <h_scrn-1
    [...]
    jmptabh  .dd1    >h_new
             .dd1    >h_hgr
             .dd1    >h_hgr2
             .dd1    >h_scrn

For each entry, select the data item, Actions > Edit Data, type the symbol, select Low or High.  It's doable but requires some effort.  Note adjustments like "-1" are applied automatically; no need for special handling.  (As with #9, this should be part of the "tutorial part 2" that I haven't written yet.)

I believe this could be done better, along the lines of what you're suggesting.  The difference in effort between "declare a range of lines as 16-bit addresses" and "set the symbol manually on every low/high part" is substantial.

**Comment by oziphantom** [comment]
If you don't know this tool https://csdb.dk/release/?id=149429 you might want to give it a whirl ;)

**Comment by oziphantom** [comment]
How does it know to apply the -1 automatically?

**Comment by fadden** [comment]
I wasn't familiar with Regenerator.  I'll take a look.

SourceGen automatically applies an adjustment whenever the symbol's value and the operand's value aren't the same.  If you tell it that `LDA #$20` is loading the low byte of `FOO`, where FOO's value is $1621, it does the math and outputs `LDA #<FOO-1`.

You can stuff any symbol you like in there and it'll output an expression that makes it work.

**Comment by oziphantom** [comment]
and if you have a label that is both +1 and -1 ?

I want the tool to make the label for me, if I have to sit here and manually look up each byte and match it and type a label by hand for it.. I don't have all year... Click the start, click the end. Make Hi/Lo or Lo/Hi then if those are to be labels. Then while the lot is selected "make lookup" get it done in 3 steps ;)

**Comment by fadden** [comment]
I absolutely agree that dealing with split data tables needs to be a thing.

The tricky part is that data format edits in SourceGen assign a format to a range of bytes at a specific offset.  When you select 20 consecutive bytes and format them as 16-bit addresses, you get 10 pairs of bytes each of which is individually tagged with the "numeric / address" format.  These act as numeric references, which cause auto-labels to be generated at the target locations if there's not one already present.  (You can see this in action in the demo video.)

(The rules for nearby target selection are ad hoc, but tend to favor labels at earlier addresses.  For things like PEA there's an explicit rule that checks one byte forward to get LABEL-1.  Some of this is mentioned in the "automatic use of nearby targets" section in intro.html in the Help.)

To format a split hi/lo table I have three choices:
 1. Treat the entire table as a single element.
 2. Define a new kind of data format that describes a 16-bit value stored in non-adjacent locations, with a pointer from the first to the next.  The format is applied to individual elements.
 3. Continue to treat things as individual bytes, but format each byte as #<symbol or #>symbol.

Option (1) requires creation of a new format type.  We already have multi-line strings and dense-hex, so it's not too different, though things like the cross-reference generator would have to know how to dig out all the addresses.  Things get ugly if there's a gap between the end of the first table and the start of the second table, but maybe that's sufficiently rare that we don't need to handle it.

Option (2) creates all kinds of weird edge cases.  My brain hurts thinking about how this would work.

Option (3) is straightforward but perhaps inconvenient.  The trouble with it is we can't stick symbols on the bytes unless the symbol has been defined, and auto-labels are only generated if there's a numeric reference to the full target address.  It's much more convenient to format the lo/hi table and then go look at the addresses it's referencing.  We could work around this by having the editor create permanent labels for each address, and then referencing those.

(There's also a hybrid of (1) and (2), where each part of the table is an individual collection, and you somehow pair collections to form a larger oh it burns it burns make it stop.)

I'm leaning toward (3) with the generate-permanent-labels feature because the on-screen display list most closely resembles what the generated assembly will look like.  It works fine if the lo and hi parts of the table aren't adjacent in memory -- the data operand format editor already handles data split across multiple regions.  It doesn't require creation of a new kind of format that breaks things.  I'd worry about spraying "permanent" labels around in the case where the user selects the wrong range of bytes and the labels go funny places, but I built a really nice "undo" system. :-)

**Comment by oziphantom** [comment]
Well it gets worse.. consider this case

```
lda #$40
sta $02
ldx $05
lda Table,x
sta $03
lda #40
ldy $04
sta ($02),y

Table .byte $00,$28,$50,$78
```

So in this case when we add more labels we get
```
lda #>ScreenRow1
sta $03
ldx $05
lda Table,x
sta $02
lda #40
ldy $04
sta ($02),y

Table .byte <ScreenRow1,<ScreenRow2,<ScreenRow3,<ScreenRow4
```
Because the all have the shared HI Byte

**Comment by fadden** [comment]
There's a point where the "automatic" stuff gets so convoluted to specify that it's not actually useful, because only three people can figure out how to make it work.  The basic split address table seems like a pretty common thing.  (Handling it was part of the feature list at one point, but it fell off somewhere along the way.)  Variants like the above could be handled by having an option to replace the high byte with a constant value.  Anything more complicated would probably just require the user to do manual edits, or we'd need to find a way to define extension scripts to solve it.
