### ISSUE TITLE
Inconsistent use of BIT to hide?

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#101]
Using BIT ($2c) to give different entry points of a different routine a unique entry value is not too uncommon and the disassembler does a great job in displaying this like so:

![image](https://user-images.githubusercontent.com/28536010/127771264-59270dc2-10fe-454a-b515-227f6de802b6.png)

Here it however doesn't and I can't see what is different that would call for different handling :

![image](https://user-images.githubusercontent.com/28536010/127771326-8113cf13-6247-4aba-a2a6-3e54149de49a.png)

**Comment by fadden** [comment]
The difference is that you haven't uncovered the code that calls address $82f8, so at this point the code analyzer just sees the BIT.

**Comment by BacchusFLT** [comment]
OK - this also explains why this is, where it has parsed them differently.

![image](https://user-images.githubusercontent.com/28536010/127776593-06114186-4676-45da-88ab-525b435d4926.png)

This is on the first example that the address in the table IS the place where the code is called. In some cases there are no other jumps to that address. How to I enforce it to be the address hidden by the BIT if there is no jump or branch to it?

**Comment by fadden** [comment]
If there are no other jumps to the address, there's no reason to expose it, because that path is never taken.  If you expect that you'll find one eventually and want to get ahead of the game:

 1. select $8ea5 and Ctrl+H Ctrl+D to mark it as code-stop; this gives you access to the individual bytes
 2. select $8ea6 and Ctrl+H Ctrl+C to mark it as code-start
 3. select $8ea5 and Ctrl+H Ctrl+R to remove the code-stop you added in step 1

**Comment by BacchusFLT** [comment]
Just for clarity - just doing the code start on the first address that
isn't parsed as code, how is that different from just doing step 2? Adding
the stop in step 1 and then deleting it again in step 3 doesn't make sense
to me, unless that is the only way to achieve something.

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 www.bergatrollet.se


Den sön 1 aug. 2021 kl 18:13 skrev Andy McFadden ***@***.***>:

**Comment by fadden** [comment]
The start/stop gymnastics are required because you can't select a mid-instruction byte.  You need to put the code-entry marker on $8ea6, but $8ea5 is treated as a single 3-byte unit, so you need to break it apart by effectively declaring it to be data, setting the code-start on the middle byte, and then removing the data declaration.

The UI could have a feature that lets you tag the 2nd/3rd/4th of a multi-byte instruction, or some sort of "explode this into one byte per line" feature", but this should be a very rare operation, since these things are normally found automatically.  Once you have the code that jumps to $8ea6 uncovered, everything will just fall into place.  It's generally better to wait for the code to be found because, until you find the part that branches to $8ea6, you don't actually know that it exists... it's possible the code was pulled in from a library and not all features got used.  You may not want to wait, or you may want to show all possible entry points in the disassembly even if they're not used, so you have the option of overriding it manually.

Code start points aren't meant to be used much.  They're really a way of saying, "code outside the program calls here", which means that the state of the status registers can't be known.  (That situation matters more for 65816 code, where the state of the M/X bits determines the length of certain instructions.)  Usually if code isn't being found it's because there's a jump table that needs to be formatted, or inline data that needs to be side-stepped.  Sometimes you get self-modifying code or a JMP (indirect) and you have to deal with it by hand; that's where you have no choice but to tag the code.

**Comment by BacchusFLT** [comment]
Many thanks - I see the point in using a workaround to access the
inaccessible.

I also understand the point with code start/stop. After working with other
tools that are a LOT less smart, I am used to manually selecting it all, so
seeing something that is code an not being meant to define it as code is
that itch where you are not supposed to scratch, but basically can't stop
yourself ;-)

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 www.bergatrollet.se


Den sön 1 aug. 2021 kl 22:46 skrev Andy McFadden ***@***.***>:
