### ISSUE TITLE
Multi line select + scrolling

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#105]
Using keyboard selecting lines (hold shift and press cursor down), when you get to the bottom of the screen and the list scrolls, the selection turns to be only one line.

**Comment by fadden** [comment]
The culprit is `ItemContainerGenerator_StatusChanged()` in MainWindow.xaml.cs.  The method exists as a work-around to a different problem (fixed in 131d1a7a6376789265464d7f7e1e00e6601a3105), which then caused another problem (issue #52, fixed in 2ddd3b400d5d4a60fb4109ac5642b4196be0c198).  If I comment out `item.Focus()`, selecting text behaves normally.

What I'd like to do is find a better fix for the original problem.  The root difficulty is that the ListView selection and keyboard navigation aren't closely coupled, and certain actions appear to cause the keyboard position to be zeroed, and you jump to the start of the project when you hit a key.  Somehow calling `Focus()` on the right thing at the right time fixes the glitch, but it seems to be screwing up other things.

**Comment by fadden** [comment]
Fixed in https://github.com/fadden/6502bench/releases/tag/v1.7.5-dev4
