### ISSUE TITLE
HuC6280 disassembly support

### ISSUE THREAD

**Issue by TheRealHamtaro126** [fadden/6502bench#106]
Hello, This disassembler is a great work, but what it needs is some sort of HuC6280 support, Can you support it please?

It's Hudson's version of the 65c02 processor, With enhancements.

Thanks for all the effort in making the Disassembler possible!

**Comment by fadden** [comment]
Looking at [this page](http://archaicpixels.com/HuC6280_Instruction_Set), it uses the W65C02 instruction set (65C02 + Rockwell) and adds several more (block move, register swaps, etc).  One of the unused status flags becomes the 'T' flag, which affects certain instructions; that would need to be taken into account for some of the status flag updaters.

Creating a CPU definition with the new instructions is doable.  SourceGen only allows you to format one operand per instruction, something that impacted BBR/BBS (issue #92); that gets a little worse here because there are more instructions with multiple operands (TST and the block moves: TIN, TII, TIA, TDD, TAI).  For the block moves you'd want labels for the source and destination arguments.  So ideally the whole "one operand per instruction" limitation would get resolved before this is done.

An MMU allows access to 2MB of RAM.  I don't know if anything would need to change to deal with this.  The instructions still only access 64KB at a given time, so probably not.

Of the four supported cross-assemblers, I believe only cc65 supports the HuC6820.

I'd say it's feasible but non-trivial.

**Comment by fadden** [comment]
Moved to wiki (https://github.com/fadden/6502bench/wiki/TO-DO-List).
