### ISSUE TITLE
.fill options

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#116]
In a program I mess with, there was a huge big block of zeros. 6502bench correctly converted them to ".fill 2203,$00". Given that I am very keen to work in all hex, the number of bytes in decimal annoyed me but I found no way to have that expressed in hex. Is there a way? The area is set to "default". In the Operand menu I can of course set it to something else, but then it won't be a ".fill" but the block of bytes.

**Comment by fadden** [comment]
There's no way to specify the format of either operand.

I went with decimal for one and hex for the other by default because "`.fill $20,$40`" might be 64 instances of $20 or 32 instances of $40 if you don't have the operand order memorized (or worse, your favorite assembler does it the other way around).  A decimal count followed by a hex byte value felt natural and unambiguous.

I already have a "TO DO" item for the second operand, because it would be nice to say "`.fill 80,'*'`" for a line of asterisks.  I can add this to the list.

**Comment by BacchusFLT** [comment]
Not sure different base will help you remember which is which if you don't know in the first place.

(When I code it's quite often patching someone else's code and I tend to use it to fill areas of garbage so the end result will pack better. So my general usage is ".fill <wherever it ends>-*,$00" (fill from where we are now until the end address given)).

**Comment by fadden** [comment]
> Not sure different base will help you remember which is which if you don't know in the first place.

Representing the fill value as hex is natural in an assembly program; if I want to fill memory with $2a I will write $2a, not 42.  The fill count could go either way, but I think somebody seeing one decimal operand and one hex operand will intuitively assume that the hex number is the fill value.

FWIW, if you're adding bytes to pad to a specific alignment, the ".align" directive will do the trick.  It turns into a fill directive, a bulk-data directive, or an alignment directive depending on the contents of the region and the capabilities of the assembler.

Semi-related: v1.8 introduced an "uninitialized data" directive, so you can document that a collection of bytes hold data that is initialized by the program before first use (which means the values in the file don't actually matter).  Before you just had to mark it as bulk data or junk.  This should replace ".fill" for many common uses, where a "variable stash" area is set to hold a bunch of 1/2/4-byte values but is initially just zero-filled.

**Comment by fadden** [comment]
Moved to "TO DO" wiki.
