### ISSUE TITLE
More on pseudopc regions

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#117]
The pseudopc region aspect works well in my new tests of the aspects.

There is one minor aspect; 

* There is no way I can change the length of the selection, is there? If I would like to move the .adrend, the only way I saw was to delete the region and start over. I would welcome a way to edit that without having to start fresh with a new region.

**Comment by fadden** [comment]
https://6502bench.com/sgmanual/editors.html#address

"If you select multiple lines, and the first line is an address region start directive, you will be able to resize that region to the selection. By definition, the updated region will have a fixed end point."

The key is that you have to select the .addrs line.  That's how the interface tells the difference between resizing an existing region, and creating a new region inside the existing one that shares a start point.

The one thing you can't do is relocate an existing region, i.e. move the .addrs line.  This was more complicated UI-wise, and seemed less useful, since the start point tends to be easy to identify.

**Comment by fadden** [comment]
BTW, if you select multiple lines, the Info window in the bottom right now tells you the size of the selection (based on the number of bytes spanned, from the first byte of the first line selected to the last byte of the last line selected).  I found this helpful when trying to select N bytes of data.

**Comment by BacchusFLT** [comment]
Many thanks for the clarification - I guess this means that topic could be closed, as there is a way.
