### ISSUE TITLE
"Fill until"

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#122]
Currently the Data Operand view will allow you to define a data area in several ways, but not necessarily all that would be needed.

Defining the data so that it assembles is one thing, but defining it so that you can start working with the code and not having it break is another.

Let's say you have code that ends at $3f80 and then you have a set of graphics that starts at $4000. The options I see is fill with 0, make it uninitialized or define it as junkbytes, possibly with an alignment.

Anything that gives a fixed number of bytes means the resulting code will break if you add a single byte to the code at $3fxx. So that will create a disassembly that works, but you can't work with it. So fixed number of bytes padding is not recommendable unless the data is static.

In KickAssembler I would do a ".fill $4000-*,$00" to define "fill from here to $4000 - not including". Then I could add stuff until the fill would overflow as my code was spilling over the defined end address.

Align does work (it's dynamic) but only in the cases where the end is at a static even $800 or $1000. If my example would seek to fill between $3f80 and say $4012, that wouldn't work either.

**Comment by fadden** [comment]
I think a "fixed length vs. fixed end point" checkbox in the bulk data section would solve it?  Kind of like the "relative" checkbox on an address region.  Should be straightforward, since it's really just passing a flag to the source code generator.

Actually, I think this could be a special case of "align".  You wouldn't use "align" and "relative" at the same time, so it would effectively be "align to arbitrary end point".  Doing it that way would simplify the way it's handled internally, since we're already passing the alignment factor around.

**Comment by BacchusFLT** [comment]
Agree. I like it when you have analysed and concluded it way better than I
could :)

Den ons 24 nov. 2021 12:05Andy McFadden ***@***.***> skrev:

**Comment by fadden** [comment]
Poking at this a little more now that MC is out the door...

I'm liking the "special case of align" internal implementation concept less, because it feels like overloading the field.  "Format descriptors" have a type and a sub-type; for junk bytes, the type is Junk and the sub-type is either None (for arbitrary length) or Align64/Align128/Align256/etc.

What we're talking about here is still structurally Junk / None.  We're not changing how SourceGen sees the bytes, we're changing how the asm source generator outputs the pseudo-op.  So this should be an additional attribute on the format descriptor, which makes it a slightly larger change.

Having said that, I think presenting it in the UI as a special case of align is still reasonable.  The dialog currently says "Junk bytes, end aligned to [arbitrary boundary]".  Adding a new option to the pop-up that says "[fixed end point]" might be less confusing than having a separate checkbox or radio button.  The alternative would be to go completely the other way, splitting it into three radio buttons:
```
    [ ] Junk bytes, fixed-length field
    [ ] Junk bytes, fixed-end field
    [ ] Junk bytes, aligned to [options]
```
It's more obvious, because all choices are laid out at once, but now the dialog is starting to sprawl.

There's a follow-on issue that needs consideration.  The examples you gave used numeric addresses, but for in-file locations you'd want to use a label.  `.fill $4000-*,$00` is okay when things are filling to a fixed location, e.g. you're writing a ROM that needs a bit of padding before the 6502 vectors at $fffa-ffff, but you might want `.fill NEXT_CHUNK-*,$00` if it's something in the file.

We'd probably want to use the label if one has been defined for the file offset that follows the junk region.  It gets a little trickier when things happen on or across address region boundaries.  The "label - *" math is a little confusing, especially when "real" vs. "virtual" PCs are involved.  I would guess that most uses will be padding to a boundary, so an address region pre-label would be the right answer, but even that won't help if we're trying to add padding out to the end of the file.  We might need to invent "post-labels" for that.

Mostly what I'm saying is nothing is ever simple. :-)

**Comment by fadden** [comment]
Moved to [TO DO list](https://github.com/fadden/6502bench/wiki/TO-DO-List).
