### ISSUE TITLE
Code starting points

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#126]
In the "Edit Operand Data" menu, selecting a word, that word could be set to an address.

* Setting it to a symbolic reference that doesn't exist, you get an error. If that happens, how about a requester, offering to add the symbol? In 99% of the cases where I received the error that is what I wanted to do.

* Setting it to and address works fine. This is what you want to do in case you have pointers to data. But sometimes the tables are jump tables, where the address is the destination for code to start. I would like to see an option to define the address also to be an implicit code start.

**Comment by fadden** [comment]
The Edit Data Operand dialog could do with an overhaul ("Streamline the data operand editor" in the to-do list.).  FWIW, the Edit Instruction Operand dialog used to look like this (v1.2):

![old-dialog](https://user-images.githubusercontent.com/6185696/165151757-17335d27-de15-4401-a212-0629d51a445e.png)

It's been re-worked a few times.  The data operand dialog has had some new features added but the fundamental flow hasn't changed.  It's a bit more complicated to deal with because changes can be applied to multiple offsets, which might result in a single multi-byte item or multiple single/multi-byte items.
