### ISSUE TITLE
Name labels based upon usage type

### ISSUE THREAD

**Issue by oziphantom** [fadden/6502bench#13]
for example something like 
does it get branched to 
bXXXX
jumped
jXXXX
JSR'd
jsXXXX
JSL'd
jlXXXX
is it used as a pointer lda ($XX,y), jsr (XXXX) for example
pXXXX
only written to
fXXXX
read/write
aXXXX or maybe vXXXX

**Comment by fadden** [comment]
This is a really interesting idea.

Some labels are accessed in multiple ways, e.g. self-modifying code might be stored + branched, subroutine starts might be JSRed and JMPed, but we could just pile up the modifiers (BW for branch + written, JS for jump + jsr).  Auto-generated labels can be rewritten by the code generator if they get too long for a given assembler.

We don't auto-label zero page locations unless the code lives there, but the absolute indirect reference would fit.

Right now the auto-labels are generated before the cross-reference calculations, so we'd need to go back and rewrite them in a second pass, but that seems doable.  In theory you're not allowed to reference auto-labels as symbols, so this could be an app setting (so people can have boring Lxxxx if that suits them better) rather than a project property.

**Comment by fadden** [comment]
I gave Regenerator a spin.  I see they do this sort of thing.

I found the 'a' and 'f' prefixes distracting, since those are valid hex digits.  Hex constants are always formatted as 2/4/6 bytes, so it's not actually ambiguous, but I show some hex values (notably addresses) without a leading '$', so having something that scans like hex but isn't might be confusing.  I think that avoiding A-F would be wise.

('b' didn't bother me as much because it's always in the context of a branch, but still...)

**Comment by oziphantom** [comment]
I wouldn't just keep adding the prefixs, as this will give us MFC lpstrw flashbacks. Instead make a priority system where one defeats the other. so a branch is nice but if something also jumps to it, the j. JSR bets J as we are then looking for a RTS, jl trumps all as we then need to make sure there is an rtl, p trumps f,a etc as I knowing that is is used in the context of a pointer helps loop for Lo/hi combos.

**Comment by AgentFriday** [comment]
Also, to make the symbols easier to read, it would be nice to have the option of inserting an underscore between the prefix and the address.  This could be purely visual, and possibly discarded if generating code for an assembler that doesn't allow underscores in symbols.

**Comment by fadden** [comment]
First cut: https://github.com/fadden/6502bench/commit/97a372a88415fa11eaa044b2ddeabb34d7f40792

There are three modes.  Default is "Simple" (e.g. "L1234").  "Annotated" changes the leading character and inserts an underscore, so e.g. branch targets are "B_1234".  "FullyAnnotated" goes the Hungarian route, so an address that is the target of BRA, LDA, and STA would be "BWR_1234".

I went with 'S' for subroutine calls (JSR/JSL), 'B' for any sort of branch or jump (BRA, BCC, BRL, JMP, JML), 'D' for locations referenced from data, "W' for writes, 'R' for reads.  For "Annotated", the first match wins.  Might be worth sticking an 'L' on the end in FullyAnnotated mode for 24-bit references, and possibly for Annotated as well, but I didn't do that here.

Published in [1.1.0-dev3](https://github.com/fadden/6502bench/releases/tag/v1.1.0-dev3).
