### ISSUE TITLE
Adding Commodore VIC-20

### ISSUE THREAD

**Issue by phillipeaton** [fadden/6502bench#131]
Hello,

Would you consider adding support for the Commodore VIC-20?

If not, could I achieve this myself by simply by adding a section for VIC-20 in the `SystemDefs.json` file and `VIC20-Kernal.sym65` file?

Otherwise, I can go with a generic 6502 project. 

Thanks, I look forward to trying out the tool!

**Comment by fadden** [comment]
The entries in `SystemDefs.json` just configure a few things in the project, like CPU type and initial set of .sym65 files.  It's a convenient alternative to configuring everything by hand for every new project.  I don't have symbol definitions for the VIC-20 because it's not a system I'm familiar with, so I don't have any insights into what should be included or excluded.

If you want to submit a set of VIC-20 definitions I'd be happy to have it in the project.  If not, you can just create a VIC-20-Kernal.sym65 file next to the project file... .sym65 files can live in the runtime directory or in the project directory.  The advantage of having it checked in is that other people can use it too.

**Comment by phillipeaton** [comment]
I'll have a look into it. I'm a beginner on VIC-20 myself, but if I come up something that others can use, I'll be sure to forward it on.
