### ISSUE TITLE
Suggestion: More colors on listing windows

### ISSUE THREAD

**Issue by grue74** [fadden/6502bench#134]
Code listing window would greatly benefit for options to change colors of the different elements.

For example different color for # operand would benefit greatly in readability.

LDA #$33
LDA $33

Look the same when you quickly glance at them, but the difference is huge.

Different color for labels would also help in readability when going thru the source over and over again and naming things.
Like if you're not 100% sure about some label, it would help if you could change its color to red (or something else), so it would be easy to see that you cannot thrust necessarily in the subroutine name.

So what I'm suggesting is some kind of theme editor and ability to choose color for the different elements in the listing.

**Comment by BacchusFLT** [comment]
Are you basically suggesting a syntax highlight system?

Den ons 4 jan. 2023 07:16Jarkko Lehti ***@***.***> skrev:

**Comment by grue74** [comment]
When you put it like that, more of less yes. I have been spoiled by modern editors with syntax hi-lite and code folding etc

**Comment by fadden** [comment]
My original vision for SourceGen was a digital version of the classic "Tearing Into Machine Language Code" (https://www.tinaja.com/ebooks/tearing_rework.pdf), which required a paper printout and five colored highlighter pens.  I didn't actually take that approach, but you can see the influence if you look at the colors used for Note highlighting.

One of the motivations for syntax highlighting is to visually separate elements.  We get that aspect for free because the fields are broken into separate columns, so opcode and operand never blend together.

Lack of certainty in labels is currently handled by adding a question mark to the end (mentioned in https://6502bench.com/sgtutorial/local-variables.html ).  It might be possible to automatically add color to such labels when they appear in the main list.

There are 37 different addressing modes on the 65816.  Assigning each a different color would be tricky.  Dividing them into categories, like immediate constants vs. addresses, is viable.  Sometimes it can be a bit muddled, e.g. PEA, but it's mostly straightforward.

The real trick with syntax highlighting is doing enough to be useful, but not so much that the screen turns into an angry fruit salad.

**Comment by grue74** [comment]
This kind of minimalistic approach was on my mind when making this suggestion. You are correct that less is more on this subject.

![image](https://user-images.githubusercontent.com/43750721/210709886-920772f2-77a6-4ebf-a1df-41a45ae4b1d3.png)
(Screenshot from my text editor)

**Comment by fadden** [comment]
Something along the lines of:

- Draw comment text in mild green, for both long comments and end-of-line comments.
- Labels in a mild blue, for the label column and the operand column.
- Immediate constants in red-orange.
- Numeric addresses in a dark maroon.
- Everything else in default foreground.  No highlighting on bulk data items.

(I'm looking at Visual Studio's color choices for inspiration.)

Instructions could get some color, e.g. highlighting conditional branches instructions could be helpful to see the control flow.

Colors would be chosen for white background and adjusted programmatically for "dark mode", as is done for Notes.  Some care must be taken with interactions with the dynamic highlighting, e.g. when the current line has an address reference, the target address and label are highlighted.  Color map could be stored in the app settings file to allow customization by motivated individuals; not sure this warrants a full syntax colorization editor UI.

The feature would be optional, enabled with a checkbox in the app settings.  The colored text could be generated in the HTML output as well (possibly with an independent setting, since it would increase the size of the output file by a fair bit).

**Comment by fadden** [comment]
Items moved to https://github.com/fadden/6502bench/wiki/TO-DO-List
