### ISSUE TITLE
Offset support to Format Address Table

### ISSUE THREAD

**Issue by grue74** [fadden/6502bench#143]
I have an address table that is offset to a fixed address.

![image](https://user-images.githubusercontent.com/43750721/218327809-f51c1f44-3e17-4dc8-a29e-c24145b31311.png)

It would be beneficial to have the option to add an address to those offsets shown in the screenshot.

In this case, the offset is $9200, and the first entry should become 9200+174 = $9374

I went through this by making labels for offset addresses, assigning them in Edit Data Operand, and using the label as Symbolic Reference. Lots of manual work could be avoided with modification in the Format Address Table tool.

**Comment by fadden** [comment]
That should be straightforward.

You may be able to work around this with a bit of trickery:

1. Select the region that is the target of the table and define a new address region, with a starting address of zero.  This aligns the addresses with the table offsets.
2. Format the address table.
3. Delete the address region.

The Txxx labels are symbolic references, so they'll get adjusted when the addresses change.

This may be awkward to do if the target region overlaps with other parts of the code.

**Comment by fadden** [comment]
Implementation notes:

- Add a text entry box to input the offset.  Allow hex or decimal to match the other boxes in the dialog.  Default to empty string (value=0).
- Value should be 16-bit.  I'm not sure if a 24-bit offset would be useful for 65816 code, since targets rarely straddle banks (setting the Bank Byte Source to a constant usually works).
- Value is simply added to address before the address-to-offset calculation.  If not 65816, treat result as mod 65536, so it wraps around at the end of the bank.  This also allows for large values to act as negative offsets.  We may want the same behavior for 65816 as well (again, crossing banks is rarely useful for address tables).

**Comment by fadden** [comment]
Moved to [TO DO wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
