### ISSUE TITLE
Enable making of WORD data types

### ISSUE THREAD

**Issue by mstr-** [fadden/6502bench#15]
![image](https://user-images.githubusercontent.com/3702893/46408191-f5fe6580-c719-11e8-8285-d114d4dca898.png)

I can't change the address here to 16-bit word.

**Comment by fadden** [comment]
You need to select an even number of adjacent bytes.  At the top of the dialog it says "1 bytes(s) selected", so you only get single-byte formats.

The tutorial has an example of formatting multiple words in one shot, and also shows what happens when your selection spans a label; see the Editing Data Formats section.

**Comment by fadden** [comment]
FWIW, over in issue #11 it was proposed that we add a keyboard shortcut for formatting data as a word.  It would grab two bytes even if only one was selected.
