### ISSUE TITLE
Use of property with same name as class

### ISSUE THREAD

**Issue by llandyw** [fadden/6502bench#18]
In ScriptManager.cs, DomainManager is a class that's also declared as a property.

This is used in member PrepareScripts.  While it does work, it's not good practice to use a class name as a property (or variable) as it's rather confusing to anyone looking at the code.  Especially if something other than VS is used to look at the code.  VS doesn't hilight it when it's not a class name, but it stuck out like a sore thumb here.

**Comment by fadden** [comment]
I've probably done that in multiple places.  I've spent most of my time writing C/C++/Java, with some C# in Unity 3D, but haven't embraced features like properties to the extent I have in SourceGen.  Looks like I called the DomainManager's PluginManager property "PluginMgr", so I'm doing it right sometimes and wrong other times.

Of course, app domains are [deprecated](https://github.com/dotnet/coreclr/issues/642) and not included in .NET core, so the entire sandbox implementation will need to be replaced eventually.  Which is too bad, because despite some problems with leases it did exactly what I wanted.

Anyway, I'll fix this one, and update others as I run across them.

**Comment by fadden** [comment]
Regex to the rescue:

    find . -name '*.cs' -print0 | xargs -0 egrep '\b(\w+)\s+\1\b'

Curiously, it found one this one too:

    ./Properties/Resources.Designer.cs:        internal static global::System.Resources.ResourceManager ResourceManager {

**Comment by fadden** [comment]
OTOH, the accepted answer here says the practice is fine: https://stackoverflow.com/questions/1095644/should-a-property-have-the-same-name-as-its-type

Apparently this is known popularly as a "Color Color" situation, because of a canonical example in .NET.  I'm learning all sorts of things. :-)
