### ISSUE TITLE
Add Vector attribute / semantics for symbols

### ISSUE THREAD

**Issue by AgentFriday** [fadden/6502bench#21]
On the C64, and I'm sure other plotforms as well, there are some vector address that you can be sure always point to code.  Programs can take over certain functions (LOAD, SAVE, ERROR, IRQ) by pointing these vectors to custom routines.

Would be nice if the idsassembler could automatically recognize addresses directly stored in these vector locations as JMP references (code hints), which would then automatically generate labels and generate `<routine` and `>routine` operands for the immediate values stored in the vectors...

     lda     #$16
     sta     VEC_LOAD
     lda     #$c1
     sta     VEC_LOAD+1

would then become something like:

     lda     #<J_C116
     sta     VEC_LOAD
     lda     #>J_C116
     sta     VEC_LOAD+1

Suggested syntax in sym65 file:

    vecName      ^   address

**Comment by fadden** [comment]
Interesting idea.  The "to do" wiki currently has this item:

- Identify common patterns, like "LDA #<label / STA ZP / LDA #>label / STA ZP+1", and apply appropriate formats automatically.

This would be a more general solution.  However, it's also more difficult to implement and more prone to false-positives than an explicit "yo, people stick addresses here" annotation.

My inclination would be to try to solve it generally, but use this as an alternative approach if the general solution turns out to be infeasible or annoying.

**Comment by fadden** [comment]
Moved to https://github.com/fadden/6502bench/wiki/TO-DO-List
