### ISSUE TITLE
No way to give single address "code hint" on automatically recognized .str

### ISSUE THREAD

**Issue by AgentFriday** [fadden/6502bench#24]
Since the act of hinting as code is essentially a "veto" of that address being interpreted as data, it would be nice if the automatic grouping of such non-data was also considered to be a mistake...  

Seems like this would be correct >99% of the time, and if not then a subsequent code hint on the operand could be explicitly given.

**Comment by fadden** [comment]
I've gone back and forth on this in my head a number of times.  On the one hand, if you select a bunch of bytes and choose an action, that action generally applies to all selected bytes.  On the other hand, you rarely, if ever, want to tag multiple consecutive bytes as code entry points.  (At one point I was going to put up a "are you sure you want to tag multiple bytes as code" dialog, but that seemed irritating.)

One way to deal with this is to use the Ctrl+B "toggle single-byte format" option on the string to split it into bytes.  This is slightly weird in that it'll leave "format as single byte" format items on a bunch of instructions, which get ignored because they shouldn't be there.  (Technically, they cause the app to crash, but I just uploaded a fix for that.)

Another way is to turn off the feature that automatically identifies strings, but that seems a little heavyweight.

The only hint you really want to apply to every byte in the selection is inline data.  Data hints are really "code analyzer stop points", and don't need to be applied to consecutive bytes.

I think the right thing is to tag the first byte on every selected line.  You can still tag multiple items in one shot, but you don't get a storm of unwanted embedded instructions.

**Comment by fadden** [comment]
Fixed in two ways (https://github.com/fadden/6502bench/commit/9be99a7cac741b83fb44cb78693a2c13f9ce926f):

- code/data hints are only applied to the first byte of each selected line
- added a keyboard shortcut to toggle .STR/.FILL generation on/off
