### ISSUE TITLE
Symbol files: Additional information

### ISSUE THREAD

**Issue by 42Bastian** [fadden/6502bench#28]
I suggest to add hints inside the symbol files about the type of symbol
*ZP
PTR @ $10

*ABS
LPTR @ $12

*CONST8
NL @ 10

*CONST16
CR @ 13

*CODE
PRINTF @ $f000

=> lda #13 will not be disassemble as lda #CR but rather lda #<CR

**Comment by fadden** [comment]
Stuff like `lda #13` is tough to do well; in a larger project there may be multiple things that match.  It could be part of a 16-bit address, it could be one of a number of constants.  We want to automate as much as possible, but if we go overboard then people will spend all their time undoing things that aren't right, or won't notice that the code is wrong and will wonder why things get all wacky when they modify the assembly output.  This is why constants (i.e. `CR = 13` rather than `CR @ 13`) are not applied automatically.

We could have an IntelliSense-style suggestion mechanism that would auto-fill known constants on request, or maybe generate a pop-up menu with a list of matching constant values that you could pick from.  We could also have a project-level, "seriously, 13 is *always* CR" type of thing; if you do it in the per-project symbols it's a choice you're clearly making, not a choice you're importing.

Yet another option is to define a standard set of ASCII control constants (CR, LF) that are universally available, and output those when the operand format is set to ASCII.

**Comment by fadden** [comment]
Moved to https://github.com/fadden/6502bench/wiki/TO-DO-List
