### ISSUE TITLE
Question regarding class instantiation

### ISSUE THREAD

**Issue by llandyw** [fadden/6502bench#32]
Andy,

I've noticed a few places where a class is instantiated, then following it, there's initialization code.
I'm wondering why there's no overloading with optional parameters being used for some of these.

An example is ProjectLoadIssues.  Standard instantiation :
                ProjectLoadIssues dlg = new ProjectLoadIssues();
                dlg.CanCancel           = false;
                dlg.Messages            = messages;

By adding the overload:

        public ProjectLoadIssues(string messages, bool cancel = true, bool cont = true)
        {
            InitializeComponent();
            Messages = messages;
            CanCancel = cancel;
            CanContinue = cont;
        }

the instantiation can be either the original (unless you make Messages, CanCancel and CanContinue private) or the following:

                ProjectLoadIssues dlg = new ProjectLoadIssues(messages, false);

or
                ProjectLoadIssues dlg = new ProjectLoadIssues(messages, false, false);

Just curious..

Andy

**Comment by fadden** [comment]
There's a haphazard mix of constructor arguments and post-construction property setting, without much rhyme or reason to it.  I wouldn't read too much intent into anything. :-)  I was trying to figure out how best to write WinForms/C# code while writing WinForms/C# code, and it's probably obvious that my understanding evolved over time.

The `ProjectLoadIssue` class should take an enum with three possible states (CanCancel, CanContinue, CanCancelOrContinue) so that it's obvious at the call site what's happening -- it's kind of annoying to run into `DoSomething(false, false, true, false, 42)` and have to figure out which boolean means what -- and also to present an API that doesn't allow invalid states (disabling both buttons doesn't make sense).  The enum and the (mandatory!) Messages string should be constructor arguments, and there should be no public properties.

**Comment by llandyw** [comment]
I feel the learining curve.  Went through it myself.  Then again when they went to .NET framework, and I still see changes, some make sense, some, not so much.

As far as the Method(false, false, true, false, 42), VS makes that easy..  As you're writing a call, you get the parameter and it's type as soon as you hit the (.  If you want to see it later, just hover over the method name and it'll show you everything.  Would be nice if it showed the info in the documentation block right before the method declaration, but we can't have anything.

Another thing I do when coding forms.  When I have radio buttons, I always create a property with a getter that returns a value for which RB is selected, and sets the proper RB depending on what's sent to it.  Sometimes I'll set up an Enum for it as well, but not usually for the simpler ones.  That way I don't have long buttonName.Checked in if statements.  I use a switch instead.  Makes for easier reading.

Something to maybe consider in the future.

**Comment by fadden** [comment]
The radio button property sounds like a good idea.  I miss `DDX_Radio()` from MFC.  (That's probably the *only* thing I miss from MFC.)  Some people have tried to do this with custom group boxes, but that doesn't seem like a good fit for this.

**Comment by fadden** [comment]
Moved various form properties into constructor args.  Cleaned up some stuff nearby while I was at it.  Haven't played with radio-button-properties yet.
