### ISSUE TITLE
Let user set the starting memory address.

### ISSUE THREAD

**Issue by mstr-** [fadden/6502bench#33]
When opening a .bin file (in c64 mode) the program reads two first bytes and uses them as load address. That might be ok with a .prg file, but if it's just binary data dumped from arbitrary address, let the user choose where to load it. (one more thing you could just do like ida)

**Comment by fadden** [comment]
Would it make sense to have two system entries for C64, one with the "use the first two bytes as address" option, one without?  If so, what should the options be called to differentiate them?  Maybe "C64 (.PRG)" and "C64 (plain binary)"?  What should the default address for "plain binary" be?

I'm doing something like this for the Apple IIgs, which has "P8" and "GS/OS" flavors.  I have zero experience with the C64, so I'm not sure what the common practices are for that system.

FWIW, all of this is just a convenience.  You can alter the load address (double-click on the .ORG) and add or remove symbol files after the project is started.  If you use "generic 6502" you won't have any of the extra stuff set.  But it's nice to have common options get set up automatically.

I haven't used Ida, so I don't know how they do things.

My eventual goal is to add "file format recognizers" that can look at the filename and file contents to get a sense for what type of file it is, and react appropriately.  For the time being the options are wired into the system definition list.

**Comment by fadden** [comment]
FWIW, you can fiddle with the definitions by editing the RuntimeData/SystemDefs.json file.  Delete the lines with "first-word-is-addr".

**Comment by mstr-** [comment]
Default address could be zero, but there should definitely be a dialog in there to select the address if loading just binary data without any special format.

Also there could be a loader for vice memory dump, which includes the whole c64 memory.

**Comment by fadden** [comment]
I wanted to avoid pestering the user with dialogs when opening the project.  I figure there's three situations:

 1. The value from the system definition is correct.  For some systems (e.g. Atari 2600) there's a high likelihood of just getting it right.  If the binary starts with a load address this is easy, though the problem is then one of identifying that the binary starts with a load address.
 2. The user doesn't actually know, and won't know until they've dug at it a bit.  So asking up front doesn't help.
 3. The default is wrong and the user knows the right answer, and will want to change it immediately.

For situation (3) it's not significantly harder to double-click the .ORG at the top of the project and set it to something else.  My inclination is to avoid putting up a dialog that is often unnecessary or unwanted, and instead just open the project file and let the user go to work.  I think the right answer depends on what percentage of the time we're in situation (3)... if it's more than half, then a dialog (or perhaps a text field on the "new project" screen) could be helpful.

A default address of zero is pretty much always wrong, because that would mean the code runs on zero page and perhaps into the stack.  I'm using a default of $1000, which is probably wrong almost as often, but doesn't treat direct-page variables as if they were part of the executable code.

I was a little worried about making "first-word-is-addr" the default because it actually does three things:

 1. Sets the initial .ORG to the start address.
 2. Adds a .ORG at offset 2, also to the start address.
 3. Formats the starts address as a 16-bit value.

So if the file doesn't start with a 16-bit load address, you have to undo the unwanted bits.  So the question isn't simply "should we ask for a load address", but also "under what circumstances should we do those three things".  Which is why I'm contemplating a separate system definition for files that begin with a load address.  I'm just not sure what C64 people call them.

**Comment by fadden** [comment]
v1.1.0-dev1 has the separate PRG/BIN system def entries.  Hopefully that'll do for now.
