### ISSUE TITLE
Simplifying code

### ISSUE THREAD

**Issue by llandyw** [fadden/6502bench#35]
Andy, I don't know if you noticed VS2017's messages on the error window, but in there it has helpful messages (sometimes helpful anyway).

But it does give info about code that can be simplified, then details when you hover over the item in the code.

For example, simplification of code when you're creating a new instance.  As an example, in ProjectView, a SaveDialog box is created, then several items are initialized.  The code now is:

```
            SaveFileDialog fileDlg  = new SaveFileDialog();
            fileDlg.Filter          = ProjectFile.FILENAME_FILTER + "|" + Properties.Resources.FILE_FILTER_ALL;
            fileDlg.FilterIndex     = 1;
            fileDlg.ValidateNames   = true;
            fileDlg.AddExtension    = true;
            fileDlg.FileName        = Path.GetFileName(mDataPathName) + ProjectFile.FILENAME_EXT;
```

can be simplified to:

```
            SaveFileDialog fileDlg = new SaveFileDialog
            {
                Filter          = ProjectFile.FILENAME_FILTER + "|" + Properties.Resources.FILE_FILTER_ALL,
                FilterIndex     = 1,
                ValidateNames   = true,
                AddExtension    = true,
                FileName        = Path.GetFileName(mDataPathName) + ProjectFile.FILENAME_EXT
            };
```

There's probably times when you would prefer the first way.  Some items can't be done the second way, if they weren't set up to be done that way.  If you try it'll tell you it can't, and why. But the second way is cleaner, with less typing!

Andy

**Comment by fadden** [comment]
I do see those messages.  I've learned a number of handy things, like how this:

    int val;
    if (thing.TryParse(str, out val)) {

can be:

    if (thing.TryParse(str, out int val)) {

which is less cluttered and defers the declaration to the point where it first needs to exist.  I liked that and use it frequently, though it's not entirely obvious that the scope of `val` is not limited to the `if` block.

Sometimes VS suggests something that just looks weird to me, e.g. some use of `=>` that shortens things up.  I tend to disregard those because, assuming the person reading it has the same started-in-C background that I have, the meaning isn't obvious, and it could lead to confusion for someone who isn't a C# expert.

The instance-initialization thing you pointed out seems like a positive.  The intent of the code will be obvious to someone who hasn't seen this style of initialization before, and it makes it clear to the reader that all of the assignments are dialog initializers.

There's a related Java pattern that I never liked, used for some factory methods, that looks like:

    obj.SetThing(123).SetAnother("hi").SetMore(3.14).SetWhatever(4567);

Each setter returns the object. so you can chain statements together.  I'm not really sure what this was supposed to accomplish; I think it makes the code harder to read.
