### ISSUE TITLE
Vectors

### ISSUE THREAD

**Issue by handyandy802** [fadden/6502bench#41]
Hi Andy,

I'm using 6502bench to disassemble a rom for an educational 6502/816 sbc.  Maybe I'm not seeing it but how does one label vectors like for example RESET, IRQBRK or NMI?

Thanks!
Andy

**Comment by fadden** [comment]
I'm not sure what you mean.  Are you adding labels to the CPU vectors at $FFFA-FFFF?  If so, does your ROM image include that area?

If it's part of the image, you just add a label to that location (double-click in label column).  Format it as a 16-bit numeric address.  This will place an auto-label at the vector target address, but doesn't automatically hint the target as code (there's a "TO DO" list item for that).  You can however double-click on the `.dd2` to jump to the target address and add a hint manually (Ctrl+H Ctrl+C).

If that memory range is not part of the image, you can add a project symbol for that address (currently Edit > Project Properties > Project Symbols, then "New Symbol").  If this is something that's common to multiple projects then it would make sense to create a .sym65 file for common use.

If none of the above is what you're after, tell me more about what you're trying to do.

**Comment by handyandy802** [comment]
Hi Andy,
The ROM image would burn into a 32k rom that resides in $8000-$ffff.  I was using it last night.  It didn't appear that I could change the data statements from .dd1 to .dd2.  I have a *.dis65 file created if you'd like to see.  It's a rom image that would be burned into a 28c256 for example.

**Comment by fadden** [comment]
Try this: select address $FFFA, then shift-click address $FFFF.  Right click, select Edit Operand.  At the top of the Edit Data Format dialog it should say, "Select data format (**6 bytes selected**)".  Click "16-bit words, little-endian", then over to the right click "Address", then OK.  You should see FFFA/FFFC/FFFE formatted as .dd2 (probably with auto-generated labels).

The data operand edit feature always operates on what's currently selected.  There's an open issue (#29) for adding a "format as word" feature, tied to Ctrl+W, that would convert the next couple of bytes to a word even if only one byte is currently selected.  (It would just be a 16-bit data item though, not a numeric reference to an address, so wouldn't simplify this operation.)

I'm wondering if I should add hover-over tooltips to disabled items on that dialog that say "this isn't available because you don't have enough items selected".
