### ISSUE TITLE
[QoL] Custom keyboard shortcut for Code Entry Point

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#55]
As I get older and start to get Carpal Tunnel having to press multiple keys across the keyboard for common actions starts to become tedious.

There should be an alternative custom keyboard for `Hint as Code Entry Point`.  Ideally one would only need to use their left hand.

Possible ideas:

* `Ctrl-1` (The `!` is a visual mnemonic for code execution) <-- First choice
* `Ctrl-E` for Entry point
* `Ctrl-Shift-F` for Function

**Comment by fadden** [comment]
I made the code hints two-key sequences because I felt like I was running out of keys, and these aren't used often.  And if you need to do a lot at once (like a series of JMPs in an API block) you can ctrl-click multiple bytes and hint them all at once.  (The only other time I've found a need for mass entry-point hinting is on a table of addresses, but there's a checkbox for that in the address table formatter.)

Seems like what we really need is configurable hotkeys, which should be possible with WPF (although WPF has a way of disappointing me).

**Comment by Michaelangel007** [comment]
Configurable hotkeys really is the best long term solution as it would solve numerous issues.

I'd be happy with a selective short fix now and general long term fix later.

* Version 1.6 add hotkeys for the common issues (Hint as function, hint as inline data, hint as smart string), and
* Version 2.0 add customizable/ configurable hotkeys for everything. Place it under `Edit` > `Preferences` ?


I also recognize the irony of an AppleWin developer asking for custom hotkeys when we don't (yet) support them. =P

**Comment by fadden** [comment]
FWIW, I'm generally reluctant to add keys to things because there aren't many "good ones", and eventually you have to start using finger-breakers like Ctrl+Shift+T for things.  Once you've added an "official" definition it becomes part of people's workflow and it's painful to remove, which potentially limits your options for keys if a new feature or path (like a command that creates a visualization set and opens the bitmap editor in one shot) is added.

A generalized key mechanism would let people do whatever they want, but requires a bit more effort to put together, especially if it needs to be fully integrated with the menu presentation.  It also lets people undo things, e.g. I changed Ctrl+D back to "delete line" in Visual Studio.

So I may be a bit hesitant about pulling changes that add new key definitions.

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
