### ISSUE TITLE
[QoL] Custom keyboard shortcut for Create/Edit Visualization New Bitmap

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#56]
Custom keyboard shortcut for `Create/Edit Visualization` > `New Bitmap` would be appreciated.

Possible Solution:

* `Ctrl-B` would be my first choice even though it is used for `Actions` > `Toggle Single-Byte Format` (which I never use)

**Comment by fadden** [comment]
I'm trying out Alt+V as the keyboard shortcut for "Create/Edit Visualization Set".  Alt+V is also how you create a new visualization in the visualization set edit dialog, so you can just hit Alt+V twice to create a new visualization at the current selection.

(The "access key" for the "New Bitmap" button is changing to Alt+V because the button is now "New Visualization".  This is happening because I'm adding visualization of wireframe meshes.  "New Bitmap Animation" gets Alt+B.)

**Comment by fadden** [comment]
I've used Alt+V Alt+V a bunch and I think it works well.  With parameters defaulting to the previous edit, and the tag string getting initial focus, you can fly through multiple similar items very quickly.
