### ISSUE TITLE
Consider renaming "Code Entry Point" to "Function"

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#64]
I'm an "old-skool" programmer having grown up with Apple ][ and HP 48SX calculator so I'm familiar with the  ` Entry Point` terminology but the name is slightly misleading for programmers new to 6502bench as it can be misinterpreted as "main".

It might be clearer if this menu option was renamed:

* `Hint as Function`

**Comment by fadden** [comment]
"Code Entry Point" reflects the idea that, in an ideal world, the hints are for places where the code is only called from outside the file.  Functions that are called from other disassembled code shouldn't need to be hinted.  Of course, in practice there are jump tables and other indirect accesses, so it's not so simple.

I expect most functions will not need to be hinted, and many entry points (such as the very first one in a game) are not functions.  Mostly I like "hint as code" vs. "hint as data", but the vagueness in "code" bothers me, because it doesn't indicate that you only need to place the hint at the point where the flow of control enters.

**Comment by Michaelangel007** [comment]
Maybe there should be two menu options?

* `Hint as Function (private)`
* `Hint as Function (public)`
