### ISSUE TITLE
Generate output from display list

### ISSUE THREAD

**Issue by 42Bastian** [fadden/6502bench#7]
If pseudo-ops are changed from the default Merlin/cc65 style, they are shown correctly but the generated code uses either Merlin/cc65 ops and not the changed ones.

**Comment by 42Bastian** [comment]
Why not add way to save this view w/o the burdon to CCP it?

**Comment by fadden** [comment]
This isn't the way I expected things to be used -- the ideal answer is to generate code for the specific assembler -- but I can see how it would be useful for unsupported assemblers (especially those that run natively rather than as a cross-assembler).  The output will likely need some editing, but possibly less editing than a cc65/Merlin 32 output file would.

**Comment by fadden** [comment]
Added File > Export, which will generate output that matches the display list.

First available in v1.3.0-dev6.
