### ISSUE TITLE
[QoL] Strings can't have Control Characters

### ISSUE THREAD

**Issue by Michaelangel007** [fadden/6502bench#71]
In the Apple ][ world it is common to have intermixed control characters (low-bit ASCII and high-bit ASCII) embedded in strings (such as arrow keys, etc.)

It is extremely frustrating that `Edit Data Operand` refuses to allow the user to mark up a string with control characters in it.

_Lode Runner_ has a null-terminated string with control characters in it.

![string_no_control_chars](https://user-images.githubusercontent.com/7876796/74752666-e35bd200-5223-11ea-82f9-d7c1d06ad2a6.png)

At the very least I want to mark this up as:

```
    .dd1 'J' | $80 ; Left
    .dd1 'I' | $80 ; Up
    .dd1 'K' | $80 ; Right
    .dd1 'M' | $80 ; Down
    .dd1 'S' + $40 ; 93 Ctrl-S Save
    .dd1 'U' + $40 ; 95 Ctrl-U ->
    .dd1 'H' + $40 ; 88 Ctrl-H <-
    .dd1 'Q' + $40 ; 91 Ctrl-Q Quit
```

There should be an addition `Display As...` option

`(  ) ASCII plus Control Characters`

This let us mark up code such as:

```
Before:    A9 01    LDA #01
After :    A9 01    LDA #'A' - $40
```

**Comment by fadden** [comment]
The string detector has a notion of "extended ASCII" that allows commonly-embedded control characters:

        public static bool IsExtendedHighAscii(byte val) {
            return IsPrintableHighAscii(val) || val == 0x87 || val == 0x8a || val == 0x8d;
        }

These are output as hex values in the assembler source, e.g. "FOO",$8d.  For PETSCII the set is larger because of things like color change codes.

Turning these into a string wouldn't make much sense, because it'd just be output as ".str $93,$95,$88", which doesn't give you anything that ".bulk" wouldn't.  The string detector requires that most of the string be printable string data in your chosen character set.

Generating single-character values with adjustments seems useful.  Might only make sense for ASCII... not sure what C64 does for control-char input.


BTW, you can change `.dd1 'J' | $80` to Merlin-style `.dd1 "J"` by updating your high-ASCII text delimiters in the app settings:
![Untitled](https://user-images.githubusercontent.com/6185696/74754658-cd034580-5226-11ea-8687-3fd56ba78640.png)

**Comment by Michaelangel007** [comment]
Thanks for the tip about High ASCII and Merlin.  I had configured it for Text String but not Character Operands!

**Comment by Michaelangel007** [comment]
In AppleWin's debugger we can do this:

```
8162:CA C9 CB CD 93 95 88 91
ASC 8162:816A
```

This is extremely compact.

Aside, that I mark up the control characters in the string as MouseText and not as Control-Characters inside AppleWin. DOH. Looks like I need to add a `TXT` directive to have strings displayed with MouseText.

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
