### ISSUE TITLE
Label format selectable

### ISSUE THREAD

**Issue by 42Bastian** [fadden/6502bench#8]
Besides the pseudo-ops it would be good to also allow choosing custom label formats in a way like:
`Local label: <prefix>label<postfix>`
`Global lable:<prefix>label<postfix>`

Where prefix/postfix can be choosen. For example, lyxass uses "." prefix for locals and "::" postfix for globals

**Comment by fadden** [comment]
The on-screen display always shows them plainly.  There's currently no support for locals in the main app -- they're "local or global" until the (theoretically assembler-specific) label localizer gets its hands on them.  There's a [TO DO](https://github.com/fadden/6502bench/wiki/TO-DO-List) item to improve that, since I'd like to see things like non-unique loop labels on-screen, but that's a bit down the road.

**Comment by 42Bastian** [comment]
Ok, get it.  Your To-do list is very long ... Anyway just an idea while using your tool.
