### ISSUE TITLE
[QoL] Merlin32 -V option

### ISSUE THREAD

**Issue by ibrumby** [fadden/6502bench#81]
Can we have a checkbox to turn on the `-V` argument for Merlin32? Either that or make it the default.

Also can we have a keyboard shortcut to auto re-run the last generate & assemble? So what is currently a 3 step process of File>Assemble, Generate, Run Assembler - have a shortcut that does the 3 in 1.

This will make my workflow much faster of making a change in the disassembler and having it appear in the emulator instantly.

**Comment by fadden** [comment]
You can add command-line arguments with a wrapper script.  I'm not particularly adept with DOS batch commands, but this seemed to do the trick:

```
@echo off
echo Running Merlin32 with -V
C:\Src\_Asm\Merlin32.exe -V %1 %2 || exit /b 1
```

Save as "wrapper.bat", change the hard-coded Merlin32.exe path to point to your binary, and change the SourceGen asm config to point to wrapper.bat instead of Merlin32.exe.

I can add an "additional arguments" text box to the assemblier config, but that sort of thing tends to get complicated because sometimes you might want the custom args to come before other args, sometimes you might want them to come after, and you can end up defining a scripting language just to specify the command line.  Wrapper scripts are less convenient but more flexible.

There's also the question of whether it's an app-wide setting or a project-specific parameter... feels project-specific, but the asm config is generally app-wide.

A single-shot gen+asm key is doable.  Are you feeding symbols into AppleWin?

**Comment by ibrumby** [comment]
Thanks for the suggestion. I didn't think of the batch file solution.

This is for feeding both symbols and source code into my emulator.
<img width="1350" alt="Stellar 7" src="https://user-images.githubusercontent.com/25833263/78467372-66db6f00-774f-11ea-8bd0-886f11a0eca5.png">

**Comment by fadden** [comment]
Shiny!

**Comment by fadden** [comment]
Migrating feature requests to [wiki](https://github.com/fadden/6502bench/wiki/TO-DO-List).
