### ISSUE TITLE
[QoL] String data formatting

### ISSUE THREAD

**Issue by roughana** [fadden/6502bench#83]
I don't like the "... at the end of the first String line.
I would like to be able to format string data so I can see all of the string data.
![image](https://user-images.githubusercontent.com/4443804/87854917-72e2e980-c958-11ea-9cf1-b78611b001c0.png)

**Comment by roughana** [comment]
Ah, I just found that widening the column showed all the data eventually. Sorry for the noise.

**Comment by fadden** [comment]
FWIW, I think there's still an opportunity to make this better by making the line-wrap point of the Operand field configurable.  Right now you have to choose between "..." in your operand and having Comment way over to the right.  Right now it's fixed at 64 chars.

It requires re-flowing all of the strings in the project because it potentially changes the number of lines, so it's not something you'd want to do dynamically as the column is resized, but it could easily be an app setting.
