### ISSUE TITLE
W65C02S disassembly mode is missing RMB/SMB instructions

### ISSUE THREAD

**Issue by philpem** [fadden/6502bench#87]
I'm using 6502Bench to disassemble some code which was built for the WDC 65C02S. It makes extensive use of the "RMB", "SMB", "BBR" and "BBS" instructions. These are opcodes 0x?7 (0x17, 0x27, ... 0xF7) and 0x?F (0x1F, 0x2F, ..., 0xFF). 

They're shown on page 22 (Opcode Matrix) of http://datasheets.chipdb.org/Western%20Design/W65C02S.pdf

When 6502Bench encounters one of these opcodes, the disassembly stops, and further code is not disassembled.
I found this suprising as I'd selected the W65C02S processor in the project options.

I checked the source code and there appears to be no support for these opcodes (unless I was looking in the wrong file)

Could support for these opcodes be added to 6502Bench?

**Comment by fadden** [comment]
These are documented in Appendix C of Eyes & Lichty as part of the "Rockwell 65C02" instruction set.  I didn't think WDC's chips supported those instructions, but apparently they do.  According to Wikipedia, they were:

> not part of the original 65C02 specification and not found in versions made by WDC or its other licensees. These were later copied back into the baseline design, and were available in later WDC versions.

So they weren't part of the enhanced //e, but are available elsewhere.  It looks like they added STP/WAI as well.

SourceGen doesn't currently support them because I've never encountered code that used them.  Supporting BBR/BBS is a little awkward because they take two arguments, which nothing else on the 65C02 does; the 65816 MVP/MVN instructions take two, but they're at least the same thing.  I can do something simple that just treats it like a branch instruction and formats the ZP arg as hex; making it work correctly is a bigger change (e.g. "edit operand" would need to let you select which operand to format).  The limited version isn't ideal, but would at least allow the disassembly to succeed.

Looks like ACME/ca65 treat BBR/BBS as 2-arg instructions, while 64tass treats it as a 3-arg instruction, e.g. `BBR 1,$17,$000c`, but I can deal with that as a special-case when generating code.

I don't think there's any need to split the CPU definition into separate 65C02 / W65C02S pieces, since it's a strict superset.

Out of curiosity, what platform is the software for?  Are you able to share a sample for testing?

**Comment by philpem** [comment]
It's a very unusual PCB from a piece of industrial equipment. It dates back to 1989 and has a 65C02 embedded inside a custom ASIC.
I suspect the code was generated by a compiler. It's the first time I've seen them used too. Very few 6502 tools aside from IDA seem to recognise these instructions.

I can probably send you some code snippets which use the instructions, but likely not the complete ROM. How large a sample would you need?

**Comment by fadden** [comment]
I'm just looking for a "real world" sample to confirm that I'm not making inappropriate assumptions about how things work, e.g. does BBR with a relative offset of zero branch to the start of the following instruction.  I don't want to rely on the behavior of other assemblers because I don't know if they tested their code on a real CPU, or just made the same assumptions I did.  A single blob of code that holds a BBR/BBS and the target address would be lovely.

FWIW, I've added the instruction definitions and a new W65C02 CPU entry, but I still need to add the DP/PCRel address mode in various places and write some unit tests.  It doesn't display the instructions correctly but at least it knows how big they are now.  From my "all opcodes in order" test:

```
1040: 16 ff                        asl   $ff,x
1042: 17 ff                        rmb1  $ff
1044: 18                           clc
1045: 19 ff fe                     ora   $feff,y
1048: 1a                           inc   A
1049: 1b                           nop
104a: 1c ff fe                     trb   $feff
104d: 1d ff fe                     ora   $feff,x
1050: 1e ff fe                     asl   $feff,x
1053: 1f ff 00                     bbr1  L1056  ;need ZP value
1056: 20 ff fe     L1056           jsr   $feff
```

**Comment by fadden** [comment]
Try this: https://github.com/fadden/6502bench/releases/tag/v1.7.3-dev1

If it works, you don't have to send me anything. :-)

There is one big gap in the support: the zero-page argument for BBR/BBS is purely decorative.  You can't format it, and it won't appear in the cross-reference list.  For all intents and purposes, BBR and BBS are simply conditional branch instructions.  I can hack around this a little, but there's a fundamental assumption in SourceGen that instructions have only one argument, and the branch target is more important (analyzer might totally miss a chunk of code).

RMB/SMB, STP, and WAI should behave correctly.

**Comment by fadden** [comment]
Have you had a chance to try it?  Does it work?

**Comment by philpem** [comment]
Sorry - I forgot to reply! Yes I've tried it, it does work. It's not identifying some of the code areas, but I think that's down to the weirdness of the code. 32K of compiled code mixed with data...!

Thanks for your help!

**Comment by fadden** [comment]
Excellent!

FWIW, there are a few reasons why code may not be identified automatically:

- Jumping indirectly through an address outside the file, e.g. storing an address in zero-page memory and jumping through it.
- Jumping to an address by pushing the location onto the stack, then executing an RTS.
- Self-modifying code, e.g. overwriting a JMP instruction.
- Addresses invoked by external code, e.g. interrupt handlers.
- Sometimes the indirect jump targets are coming from a table of addresses in the file. If so, these can be formatted as addresses, and then the target locations tagged as code entry points.

You can tag addresses as code start points to tell the code analyzer to scan them as well.  (This is currently referred to as "adding a code hint", but I'm renaming the feature to reduce confusion.)
