### ISSUE TITLE
65C02 Bitwise Branch Op-Codes Don't Use Labels for Both Operands

### ISSUE THREAD

**Issue by benboldtumd** [fadden/6502bench#92]
I ran into an issue disassembling 65**C**02 with bitwise branch opcodes.  Here is an example:

```
                   ; 6502bench SourceGen v1.7.3
                   SHADOW_4112_READ .eq    $11
                   SHADOW_4112_WRITE .eq   $12
                   CPU2_REG_4112   .eq     $4112

e4f2: 0f 11 0a     CHECK_4112_0    bbr0    $11,IRQ_DONE      ;SHADOW_4112_READ
e4f5: f7 12                        smb7    SHADOW_4112_WRITE
e4f7: a5 12                        lda     SHADOW_4112_WRITE
e4f9: 8d 12 41                     sta     CPU2_REG_4112
e4fc: 20 78 e6                     jsr     IRQ_UPDATE_7
e4ff: 6c 06 01     IRQ_DONE        jmp     (IRQ_PTR)
```

If you refer to the line CHECK_4112_0, you can see that it does not insert SHADOW_4112_READ for $11.  I am not sure this would be possible without some sort of major overhaul though, it seems the disassembler is sort of designed to have 1 label per opcode.  It is not a huge problem for me to work around (I just insert a comment for these) and I am very happy with 6502bench SourceGen.

**Comment by fadden** [comment]
This is mentioned in the README, under "limitations":

> The zero-page argument for the Rockwell BBR/BBS instructions cannot be formatted.

(That's a little disingenuous since it has other limitations, e.g. it doesn't appear in cross-reference lists either.)

The reason for it is exactly what you suspect: the design only allows for a single operand per instruction.  The only other instruction with more than one operand is 65816 block move (MVN/MVP), where it's less of a problem because both args are bank numbers.  I was aware of the existence of the instructions from an appendix in the Eyes & Lichty 65816 book, but thought they were only present on some weird Rockwell variant, so didn't pay much attention to them until issue #87.

Making it work right would require hackery in a bunch of different places.  The basic code/data analysis doesn't really change, but cross-refs, local variables, and the Edit Operand UI would need some effort.

**Comment by benboldtumd** [comment]
Sorry I had not read the readme for a while or very carefully. I think it is just fine the way it is and pretty obscure for most people to ever even run into that.  Anyway, thanks for the prompt explanation and I really like your work on this disassembler.  I actually found a 65C02 inside the Famicom Network System and it is my first time working with these extra instructions.

I am closing the issue, it definitely seems like more trouble than it is worth, and really actually works totally fine the way it is.
