### ISSUE TITLE
Issue with automatic code parsing - BCC

### ISSUE THREAD

**Issue by BacchusFLT** [fadden/6502bench#99]
In this instance, I had to force a code start of the STA $04F1,x which means it's assuming that it takes the BCC and doesn't map the following instruction as code, right?

![image](https://user-images.githubusercontent.com/28536010/127768981-811db1a4-ca70-497b-8395-a850515a7a6d.png)

**Comment by fadden** [comment]
The code snippet above cannot get to that STA: the carry is cleared, and none of those instructions can cause it to be set, so the BCC is a branch-always.  The only way to get there is via some external code path.  So you have four choices:
  1. uncover the code that branches to that point (assuming it exists); this is the preferred approach
  2. manually override the processor flags on the BCC line so it's no longer a branch-always (change the 'C' flag to indeterminate)
  3. add a code-entry point past the BCC line
  4. ignore the dead code

The carry flag gets marked as indeterminate in the above because the flags are all marked that way at code-entry points.  You made the STA $04f1,x an entry point, so all the flags from there forward are indeterminate.  Those flags then got carried back to the STA by the BPL at the end.

(Note: you can copy & paste selected lines as text; no need to screen-shot.  You can control which columns are included from the app settings.)

**Comment by BacchusFLT** [comment]
But you can enter the routine via the L87EA as well and the carry could then be set, or?

**Comment by fadden** [comment]
Yes, but since the code analyzer hasn't seen anything that branches to L87EA, it has no reason to believe that such a branch exists.  Once you uncover the code that branches there, everything will fall into place with no manual intervention.  If you don't uncover it, then it doesn't exist, and the BCC really is a branch-always and the code below it can never execute.

The various ways of overriding the behavior are intended for cases where the code analyzer can't see the branch, e.g. self-modifying code or some methods of jumping indirectly.
